V1
VitoZet/Yandex-fid-csv-presta pull request #1
Opened 2018-04-11 07:49 UTC by VitoZet

2018-04-11 14:22 UTC, dgigel requested changes
В целом то код рабочий!
Надо тестировать, гонять

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +api_key = ''
Кстати, если не хочешь париться с переменными окружения, то на первых парах эти настройки можно вынести в отдельный файл, оттуда и импортить. Допустим settings.py, который можно добавить в .gitognore.

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +from prestashop_api import PrestashopApi
Ну и замути requirements.txt, чтобы в окружении подгружать сторонние модули.

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +def id_products_category(input_categoty):
Называй функции понятнее. Комменты - круто. Из их описания я понял, что эта функция получает список id товаров из категории ~> 
get_product_ids(id_category)

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +    product_api = api.get('categories/'+str(input_categoty))
Надо подумать, а чо будет, если api.get рухнет с ошибкой?

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +    fileNoActiveID = open('NoActiveID-'+str(datetime.now().strftime("%Y%m%d-%H%M%S"))+'.txt', 'w')
PEP8
https://pythonworld.ru/osnovy/pep-8-rukovodstvo-po-napisaniyu-koda-na-python.html#id20

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +def id_on_stock(sorting_activity_id):
get product ids in stock

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +def id_combination_product(id_product):
product_combinations

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +def min_price_combinations_product_and_referance(id_combination_product, price_product_default):
reference

2018-04-11 14:22 UTC, dgigel commented on CSVFeed-Yandex.py
> +        product_api = api.get('products/' + str(id_product))
так же.. что будет, если с ошибкой вернет

2018-04-13 10:05 UTC, VitoZet commented on CSVFeed-Yandex.py
> +def id_products_category(input_categoty):
Поправил

2018-04-13 10:10 UTC, VitoZet commented on CSVFeed-Yandex.py
> +    fileNoActiveID = open('NoActiveID-'+str(datetime.now().strftime("%Y%m%d-%H%M%S"))+'.txt', 'w')
исправил на file_no_active_id

2018-04-13 10:39 UTC, VitoZet commented on CSVFeed-Yandex.py
> +def id_on_stock(sorting_activity_id):
поправил

2018-04-13 10:41 UTC, VitoZet commented on CSVFeed-Yandex.py
> +def min_price_combinations_product_and_referance(id_combination_product, price_product_default):
исправил

2018-04-13 10:43 UTC, VitoZet commented on CSVFeed-Yandex.py
> +        product_api = api.get('products/' + str(id_product))
try:
except:
print('Нет доступа по API, похоже сайт лёг')

2018-04-14 15:34 UTC, dgigel approved these changes

2018-04-14 15:46 UTC, merged